openapi: '3.0.3'

info:
  description: CSE 115a Project
  version: 0.1.0
  title: Slug Sync

servers:
  - url: http://localhost:3010/v0

paths:
  /users:
    get:
      tags:
        - users
      summary: Get all users
      description: direct messages
      responses:
        200:
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /login:
    post:
      description: Login
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    Error:
      additionalProperties: false
      required:
        - message
        - errors
        - status
      properties:
        errors:
          type: array
        message:
          type: string
        status:
          type: integer
    User:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        accessToken:
          type: string
        name:
          type: string
      required:
        - email
        - id
        - accessToken
        - name
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
