openapi: '3.0.3'

info:
  description: CSE 115a Project
  version: 0.1.0
  title: Slug Sync

servers:
  - url: http://localhost:3010/v0

paths:

  /goal:
    post:
      tags:
        - create goal
      summary: create goal
      responses:
        200:
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoalWithId'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        description: create goal
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGoal'

  /signup:
    post:
      description: User SignUp
      requestBody:
        description: User form fields
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpForm'
      responses:
        201:
          description: Successfully creates User

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: error code
        message:
          type: string
          description: error message

    CreateGoal:
      type: object
      required:
        - title
        - description
        - recurrence
      properties:
        title:
          type: string
          description: title of goal
        description:
          type: string
          description: description of goal
        recurrence:
          type: string
          description: recurrence of goal
      example:
        title: "title"
        description: "description"
        recurrence: "1"

    GoalWithId:
      type: object
      required:
        - id
        - title
        - description
        - recurrence
      properties:
        id:
          type: string
          description: id of goal
        title:
          type: string
          description: title of goal
        description:
          type: string
          description: description of goal
        recurrence:
          type: string
          description: recurrence of goal
      example:
        id: "1"
        title: "title"
        description: "description"
        recurrence: "1"

    SignUpForm:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        email:
          type: string
          format: email
          pattern: '^[\w\.-]+@[a-zA-Z\d\.-]+\.[a-zA-Z]{2,}$'
        password:
          type: string
      required:
        - name
        - email
        - password

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
